name: Latest posts workflow
on:
  # schedule:
  #   - cron: '0 * * * *' 
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://uluumbch.my.id/index.xml"
          max_post_count: 5
          template: "- `$date` | [$title]($url)  $newline"
          date_format: dd-mm-yyyy
          tag_post_pre_newline: true

  update-readme-with-blog-en:
    name: EN Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://uluumbch.my.id/en/index.xml"
          max_post_count: 5
          comment_tag_name: "BLOG-POST-LIST-EN"
          template: "- `$date` | [$title]($url)  $newline"
          date_format: dd-mm-yyyy
          tag_post_pre_newline: true
